'''
@author    : B35385
@name      : testConfiguration
@copyright : Copyright (c) 2016, NXP Semiconductors.

********************************************************************************
This is the configuration module used to store global test parameters and configuration.
********************************************************************************
'''
import sys
import lpcBoardDrv
import pneBoardDrv
import mbedBoardDrv
from buildConfiguration import BINARY_FILE_PATH

# Settings for adjusting Board selection.
BOARD_NAME     = str(sys.argv[2])
BAMBOO_REPORTS = (sys.argv[3] != '0') # Generate XML reports for Bamboo or display onscreen for manual runs.
DUT_PORT_SEQ   = int(sys.argv[4]) # Sequence number of K64F port to be selected for DUT in case of SIM Tests.
DUT_BOARD_SEQ  = int(sys.argv[5]) # Sequence number of K64F board to be selected for DUT in case of SIM Tests.
SIM_PORT_SEQ   = int(sys.argv[6]) # Sequence number of K64F port to be selected for SIM.
SIM_BOARD_SEQ  = int(sys.argv[7]) # Sequence number of K64F board to be selected for SIM.
BOARD_NAME_ADS = BOARD_NAME

# Global Parameters
SIM_MAX_SAMPLE_WIDTH   = 6 # MAX Bytes (in HEX)
SIM_CFG_SLAVE_CMD_TAG  = '00'
SIM_ADD_SAMPLE_CMD_TAG = '01'
SIM_WINDOWS_EOL_BYTES  = '0D 0A' # Windows/DOS EOL length (CR and LF as EOL in last 2 bytes).
if BOARD_NAME == "KL25Z" or BOARD_NAME == "KL27Z":
    BOARD_OBJECT_HANDLE = pneBoardDrv
    FILE_FORMAT_EXTN    = ".srec"
elif BOARD_NAME == "LPC54114":
    BOARD_NAME_ADS = "LPCXPRESSO54114"
    BOARD_OBJECT_HANDLE = lpcBoardDrv
    FILE_FORMAT_EXTN    = ".bin"
elif BOARD_NAME == "QN9080":
    BOARD_NAME_ADS = "QN908x"
    BOARD_OBJECT_HANDLE = lpcBoardDrv
    FILE_FORMAT_EXTN    = ".bin"    
else:
    BOARD_OBJECT_HANDLE = mbedBoardDrv
    FILE_FORMAT_EXTN    = ".bin"

BINARY_FILE_BASE_PATH   = BINARY_FILE_PATH + "\\"
SAMPLE_FILE_BASE_PATH   = "unittests\harness\SampleFiles\\"

FXAS21002_SAMPLE_FILE   = SAMPLE_FILE_BASE_PATH + "samples_FXAS21002.txt"
FXOS8700_SAMPLE_FILE    = SAMPLE_FILE_BASE_PATH + "samples_FXOS8700.txt"
MPL3115_SAMPLE_FILE     = SAMPLE_FILE_BASE_PATH + "samples_MPL3115.txt"
MPL3115_8K_SAMPLE_FILE  = SAMPLE_FILE_BASE_PATH + "samples_MPL3115_8K.txt"

K64F_SIM_FLASH_FILE     = BINARY_FILE_BASE_PATH + "K64F-ISSDK-Simulator.bin"

FXAS21002_FIFO_FILE     = BINARY_FILE_BASE_PATH + BOARD_NAME + "-AGM01-FXAS21002-FIFO"              + FILE_FORMAT_EXTN
FXAS21002_POLL_FILE     = BINARY_FILE_BASE_PATH + BOARD_NAME + "-AGM01-FXAS21002-POLL"              + FILE_FORMAT_EXTN
FXAS21002_INT_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-AGM01-FXAS21002-INTERRUPT"         + FILE_FORMAT_EXTN
FXAS21002_TEST_FILE     = BINARY_FILE_BASE_PATH + BOARD_NAME + "-AGM01-FXAS21002-TEST"              + FILE_FORMAT_EXTN

FXLS8962_NORMAL_FILE    = BINARY_FILE_BASE_PATH + BOARD_NAME  + "-AGMP03-FXLS8962-NORMAL"           + FILE_FORMAT_EXTN
FXLS8962_INT_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME  + "-AGMP03-FXLS8962-INTERRUPT"        + FILE_FORMAT_EXTN
FXLS8962_TEST_I2C_FILE  = BINARY_FILE_BASE_PATH + BOARD_NAME  + "-AGMP03-FXLS8962-I2C-TEST"         + FILE_FORMAT_EXTN

FXLC95000_I2C_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-SA9500-ACCEL-I2C"                  + FILE_FORMAT_EXTN
FXLC95000_SPI_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-SA9500-ACCEL-SPI"                  + FILE_FORMAT_EXTN
FXLC95000_TEST_I2C_FILE = BINARY_FILE_BASE_PATH + BOARD_NAME + "-SA9500-ACCEL-I2C-TEST"             + FILE_FORMAT_EXTN
FXLC95000_TEST_SPI_FILE = BINARY_FILE_BASE_PATH + BOARD_NAME + "-SA9500-ACCEL-SPI-TEST"             + FILE_FORMAT_EXTN

FXOS8700_FIFO_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-AGM01-FXOS8700-FIFO"               + FILE_FORMAT_EXTN
FXOS8700_POLL_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-AGM01-FXOS8700-POLL"               + FILE_FORMAT_EXTN
FXOS8700_INT_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-AGM01-FXOS8700-INTERRUPT"          + FILE_FORMAT_EXTN
FXOS8700_TEST_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-AGM01-FXOS8700-TEST"               + FILE_FORMAT_EXTN

MAG3110_NORMAL_FILE     = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MAG3110-NORMAL"             + FILE_FORMAT_EXTN
MAG3110_INT_FILE        = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MAG3110-NORMAL-INTERRUPT"   + FILE_FORMAT_EXTN
MAG3110_ONESHOT_FILE    = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MAG3110-ONESHOT"            + FILE_FORMAT_EXTN
MAG3110_TEST_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MAG3110-TEST"               + FILE_FORMAT_EXTN

MMA865x_FIFO_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MMA865X-FIFO"               + FILE_FORMAT_EXTN
MMA865x_POLL_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MMA865X-POLL"               + FILE_FORMAT_EXTN
MMA865x_INT_FILE        = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MMA865X-INTERRUPT"          + FILE_FORMAT_EXTN
MMA865x_TEST_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MMA865X-TEST"               + FILE_FORMAT_EXTN

MMA845x_FIFO_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-ONBOARD-MMA845X-FIFO"              + FILE_FORMAT_EXTN
MMA845x_POLL_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-ONBOARD-MMA845X-POLL"              + FILE_FORMAT_EXTN
MMA845x_INT_FILE        = BINARY_FILE_BASE_PATH + BOARD_NAME + "-ONBOARD-MMA845X-INTERRUPT"         + FILE_FORMAT_EXTN
MMA845x_TEST_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-ONBOARD-MMA845X-TEST"              + FILE_FORMAT_EXTN

MMA8491Q_EG_FILE        = BINARY_FILE_BASE_PATH + BOARD_NAME + "-A8491-EXAMPLE"                     + FILE_FORMAT_EXTN
MMA8491Q_TEST_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-A8491-TEST"                        + FILE_FORMAT_EXTN

DP5004_EG_FILE          = BINARY_FILE_BASE_PATH + BOARD_NAME + "-DP5004-INTERRUPT"                  + FILE_FORMAT_EXTN

MMA9553_NORMAL_FILE     = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MMA9553-PEDOMETER-I2C"      + FILE_FORMAT_EXTN
MMA9553_TEST_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-MULT2B-MMA9553-TEST"               + FILE_FORMAT_EXTN

FXLS8471Q_FIFO_FILE     = BINARY_FILE_BASE_PATH + BOARD_NAME + "-A8471-SPI-FIFO"                    + FILE_FORMAT_EXTN
FXLS8471Q_POLL_FILE     = BINARY_FILE_BASE_PATH + BOARD_NAME + "-A8471-SPI-POLL"                    + FILE_FORMAT_EXTN
FXLS8471Q_INT_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-A8471-SPI-INTERRUPT"               + FILE_FORMAT_EXTN
FXLS8471Q_TEST_FILE     = BINARY_FILE_BASE_PATH + BOARD_NAME + "-A8471-SPI-TEST"                    + FILE_FORMAT_EXTN

MPL3115_FIFO_INT_FILE   = BINARY_FILE_BASE_PATH + BOARD_NAME + "-P3115-FIFO-INTERRUPT"              + FILE_FORMAT_EXTN
MPL3115_NORM_INT_FILE   = BINARY_FILE_BASE_PATH + BOARD_NAME + "-P3115-NORMAL-INTERRUPT"            + FILE_FORMAT_EXTN
MPL3115_FIFO_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-P3115-FIFO"                        + FILE_FORMAT_EXTN
MPL3115_ALT_FILE        = BINARY_FILE_BASE_PATH + BOARD_NAME + "-P3115-ALTITUDE"                    + FILE_FORMAT_EXTN
MPL3115_NORM_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-P3115-NORMAL"                      + FILE_FORMAT_EXTN
MPL3115_ONE_FILE        = BINARY_FILE_BASE_PATH + BOARD_NAME + "-P3115-ONESHOT"                     + FILE_FORMAT_EXTN
MPL3115_STREAM_FILE     = BINARY_FILE_BASE_PATH + BOARD_NAME + "-P3115-STREAMING"                   + FILE_FORMAT_EXTN
MPL3115_TEST_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-P3115-TEST"                        + FILE_FORMAT_EXTN
MPL3115_RST_FILE        = SAMPLE_FILE_BASE_PATH + BOARD_NAME + "-P3115-RST"                         + FILE_FORMAT_EXTN

FXPQ3115_FIFO_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-B3115-FIFO"                        + FILE_FORMAT_EXTN
FXPQ3115_ALT_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-B3115-ALTITUDE"                    + FILE_FORMAT_EXTN
FXPQ3115_NORM_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-B3115-NORMAL"                      + FILE_FORMAT_EXTN
FXPQ3115_ONE_FILE       = BINARY_FILE_BASE_PATH + BOARD_NAME + "-B3115-ONESHOT"                     + FILE_FORMAT_EXTN
FXPQ3115_TEST_FILE      = BINARY_FILE_BASE_PATH + BOARD_NAME + "-B3115-TEST"                        + FILE_FORMAT_EXTN
FXPQ3115_RST_FILE       = SAMPLE_FILE_BASE_PATH + BOARD_NAME + "-B3115-RST"                         + FILE_FORMAT_EXTN

DP300x_INT_FILE         = BINARY_FILE_BASE_PATH + BOARD_NAME + "-DP300x-INTERRUPT"                  + FILE_FORMAT_EXTN
DP300x_NORM_FILE        = BINARY_FILE_BASE_PATH + BOARD_NAME + "-DP300x-NORMAL"                     + FILE_FORMAT_EXTN
DP300x_ONE_FILE         = BINARY_FILE_BASE_PATH + BOARD_NAME + "-DP300x-ONESHOT"                    + FILE_FORMAT_EXTN
DP300x_SPI_FILE         = BINARY_FILE_BASE_PATH + BOARD_NAME + "-DP300x-SPI"                        + FILE_FORMAT_EXTN
DP300x_THS_FILE         = BINARY_FILE_BASE_PATH + BOARD_NAME + "-DP300x-THRESHOLD"                  + FILE_FORMAT_EXTN
DP300x_TEST_FILE        = BINARY_FILE_BASE_PATH + BOARD_NAME + "-DP300x-I2C-TEST"                   + FILE_FORMAT_EXTN

HOST_DEMO_FILE          = BINARY_FILE_BASE_PATH + BOARD_NAME + "-AGM01-HOST-DEMO"                   + FILE_FORMAT_EXTN
