/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum)            \
    \
{                                           \
        Unity.CurrentTestName = #TestFunc;         \
        Unity.CurrentTestLineNumber = TestLineNum; \
        Unity.NumberOfTests++;                     \
        if (TEST_PROTECT())                        \
        {                                          \
            setUp();                               \
            TestFunc();                            \
        }                                          \
        if (TEST_PROTECT() && !TEST_IS_IGNORED)    \
        {                                          \
            tearDown();                            \
        }                                          \
        UnityConcludeTest();                       \
    \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "fsl_i2c.h"
#include "Driver_I2C.h"
#include "Driver_I2C_SDK2.h"
#include "sensor_drv.h"
#include "fxls8952.h"
#include "fxls8952_drv.h"
#include <string.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_fxls8952_init(void);
extern void test_fxls8952_config(void);
extern void test_fxls8952_startData(void);
extern void test_fxls8952_deInit(void);
extern void test_fxls8952_negative_1(void);
extern void test_fxls8952_negative_2(void);
extern void test_fxls8952_negative_3(void);
extern void test_fxls8952_negative_4(void);

//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
    tearDown();
    setUp();
}

//=======MAIN=====
int main(void)
{
    UnityBegin("test_fxls8952.c");

    RUN_TEST(test_fxls8952_negative_1, 0);
    RUN_TEST(test_fxls8952_negative_2, 0);
    RUN_TEST(test_fxls8952_init, 0);
    RUN_TEST(test_fxls8952_negative_3, 0);
    RUN_TEST(test_fxls8952_config, 0);
    RUN_TEST(test_fxls8952_negative_4, 0);
    RUN_TEST(test_fxls8952_deInit, 0);

    return (UnityEnd());
}
