/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum)            \
    \
{                                           \
        Unity.CurrentTestName = #TestFunc;         \
        Unity.CurrentTestLineNumber = TestLineNum; \
        Unity.NumberOfTests++;                     \
        if (TEST_PROTECT())                        \
        {                                          \
            setUp();                               \
            TestFunc();                            \
        }                                          \
        if (TEST_PROTECT() && !TEST_IS_IGNORED)    \
        {                                          \
            tearDown();                            \
        }                                          \
        UnityConcludeTest();                       \
    \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_mma845x_init(void);
extern void test_mma845x_config(void);
extern void test_mma845x_deInit(void);
extern void test_mma845x_negative_1(void);
extern void test_mma845x_negative_2(void);
extern void test_mma845x_negative_3(void);
extern void test_mma845x_negative_4(void);

//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
    tearDown();
    setUp();
}

//=======MAIN=====
int main(void)
{
    UnityBegin("test_mma845x.c");
    RUN_TEST(test_mma845x_init, 0);
    RUN_TEST(test_mma845x_config, 0);
    RUN_TEST(test_mma845x_deInit, 0);
    RUN_TEST(test_mma845x_negative_1, 0);
    RUN_TEST(test_mma845x_negative_2, 0);
    RUN_TEST(test_mma845x_negative_3, 0);
    RUN_TEST(test_mma845x_negative_4, 0);

    return (UnityEnd());
}
